
export const HOSPITAL_UNITS = [
    "Rawat Inap - Bougenville",
    "Rawat Inap - Anggrek",
    "Rawat Inap - Flamboyan",
    "Rawat Inap - Mawar",
    "Rawat Inap - Anyelir",
    "Rawat Inap - Melati",
    "Rawat Inap - Dahlia/VK",
    "Rawat Inap - Camelia",
    "Rawat Inap - Kenanga",
    "Rawat Inap - WK",
    "ICU",
    "PICU",
    "NICU",
    "IGD",
    "PONEK",
    "IBS",
    "Gizi",
    "Farmasi",
    "Kesling & K3RS",
    "Rawat Jalan",
    "Laboratorium",
    "Radiologi",
    "IPSRS",
    "SIMRS",
    "CSSD",
    "Laundry",
    "Keuangan",
    "Kepegawaian",
    "Bagian Umum",
    "Program Humas & Program",
    "PKRS"
];
