
export const HOSPITAL_UNITS = [
    "BANK DARAH",
    "BEDAH DAN ANASTESI",
    "CSSD",
    "FARMASI",
    "GIZI",
    "HD",
    "HUMAS",
    "ICU",
    "IGD",
    "IPSRS",
    "JKN",
    "KEPEGAWAIAN",
    "KESLING",
    "KEUANGAN",
    "LABORATORIUM",
    "LAB PA",
    "LAUNDRY",
    "PEMULASARAN JENAZAH",
    "PERINATOLOGY DAN OBGYN",
    "PONEK",
    "PPI",
    "RADIOLOGI",
    "RAJAL",
    "RANAP",
    "REHAB MEDIK",
    "REKAM MEDIS",
    "SIM-RS"
];
