import { type OpenAPIObject } from 'openapi3-ts'

const errorSchema = {
  type: 'object',
  properties: {
    error: { type: 'string', description: 'Pesan kesalahan terperinci.' },
  },
} as const

export const openApiDocument = {
  openapi: '3.0.3',
  info: {
    title: 'SiRatu API',
    version: '1.0.0',
    description:
      'Dokumentasi REST API SiRatu yang digunakan oleh aplikasi Next.js. Semua contoh payload mengikuti data hasil seeder.',
    contact: {
      name: 'Tim Mutu RS',
      email: 'admin@sim.rs',
    },
  },
  servers: [
    {
      url: 'http://localhost:3000',
      description: 'Lingkungan pengembangan lokal',
    },
  ],
  tags: [
    { name: 'Session', description: 'Informasi sesi pengguna.' },
    { name: 'Users', description: 'Manajemen pengguna dan peran.' },
    { name: 'Units', description: 'Data unit/instalasi rumah sakit.' },
    { name: 'Indicator Profiles', description: 'Profil indikator mutu.' },
    { name: 'Submitted Indicators', description: 'Pengajuan indikator dan capaian.' },
    { name: 'Indicators', description: 'Capaian indikator terverifikasi.' },
    { name: 'Incidents', description: 'Pelaporan insiden keselamatan pasien.' },
    { name: 'Risks', description: 'Manajemen risiko dan mitigasi.' },
    { name: 'Notifications', description: 'Notifikasi realtime ke pengguna.' },
    { name: 'System Logs', description: 'Catatan aktivitas untuk audit.' },
    { name: 'Realtime', description: 'Server-Sent Events untuk pembaruan instan.' },
  ],
  components: {
    schemas: {
      ApiError: errorSchema,
      SessionUser: {
        type: 'object',
        required: ['id', 'name', 'email', 'role'],
        properties: {
          id: { type: 'string', format: 'uuid' },
          name: { type: 'string' },
          email: { type: 'string', format: 'email' },
          role: { type: 'string', description: 'Nama peran dalam format UI.' },
          unit: { type: 'string', nullable: true },
        },
      },
      SessionResponse: {
        type: 'object',
        properties: {
          user: { oneOf: [{ $ref: '#/components/schemas/SessionUser' }, { type: 'null' }] },
        },
      },
      Unit: {
        type: 'object',
        required: ['id', 'name'],
        properties: {
          id: { type: 'string', format: 'uuid' },
          name: { type: 'string' },
        },
        example: { id: 'unit_123', name: 'IGD' },
      },
      UnitRequest: {
        type: 'object',
        required: ['name'],
        properties: {
          name: { type: 'string', description: 'Nama unit unik.' },
        },
      },
      User: {
        type: 'object',
        required: ['id', 'name', 'email', 'role'],
        properties: {
          id: { type: 'string', format: 'uuid' },
          name: { type: 'string' },
          email: { type: 'string', format: 'email' },
          role: { type: 'string', description: 'Peran dalam format UI, mis. "Admin Sistem".' },
          unit: { type: 'string', nullable: true },
        },
      },
      UserRequest: {
        type: 'object',
        required: ['name', 'email', 'password', 'role'],
        properties: {
          name: { type: 'string' },
          email: { type: 'string', format: 'email' },
          password: { type: 'string', description: 'Disimpan plaintext untuk demo.' },
          role: { type: 'string', description: 'Gunakan label UI, mis. "PIC Mutu".' },
          unit: { type: 'string', nullable: true },
        },
      },
      IndicatorProfile: {
        type: 'object',
        required: ['id', 'title', 'purpose', 'calculationMethod', 'target', 'targetUnit', 'status'],
        properties: {
          id: { type: 'string', format: 'uuid' },
          title: { type: 'string' },
          purpose: { type: 'string' },
          definition: { type: 'string' },
          implication: { type: 'string' },
          calculationMethod: { type: 'string', enum: ['percentage', 'average'] },
          numerator: { type: 'string' },
          denominator: { type: 'string' },
          target: { type: 'number' },
          targetUnit: { type: 'string', enum: ['%', 'menit'] },
          inclusionCriteria: { type: 'string' },
          exclusionCriteria: { type: 'string' },
          dataRecording: { type: 'string' },
          unitRecap: { type: 'string' },
          analysisReporting: { type: 'string' },
          area: { type: 'string' },
          pic: { type: 'string' },
          status: { type: 'string', enum: ['Draf', 'Menunggu Persetujuan', 'Disetujui', 'Ditolak'] },
          rejectionReason: { type: 'string', nullable: true },
          createdBy: { type: 'string' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          unit: { type: 'string' },
          locked: { type: 'boolean' },
          lockedReason: { type: 'string', nullable: true },
        },
      },
      IndicatorProfileRequest: {
        type: 'object',
        required: [
          'title',
          'purpose',
          'definition',
          'implication',
          'calculationMethod',
          'numerator',
          'denominator',
          'target',
          'targetUnit',
          'dataRecording',
          'unitRecap',
          'analysisReporting',
          'area',
          'pic',
          'status',
          'unit',
        ],
        properties: {
          title: { type: 'string' },
          purpose: { type: 'string' },
          definition: { type: 'string' },
          implication: { type: 'string' },
          calculationMethod: { type: 'string', enum: ['percentage', 'average'] },
          numerator: { type: 'string' },
          denominator: { type: 'string' },
          target: { type: 'number' },
          targetUnit: { type: 'string', enum: ['%', 'menit'] },
          inclusionCriteria: { type: 'string' },
          exclusionCriteria: { type: 'string' },
          dataRecording: { type: 'string' },
          unitRecap: { type: 'string' },
          analysisReporting: { type: 'string' },
          area: { type: 'string' },
          pic: { type: 'string' },
          status: { type: 'string' },
          rejectionReason: { type: 'string' },
          unit: { type: 'string' },
        },
      },
      SubmittedIndicator: {
        type: 'object',
        required: [
          'id',
          'name',
          'category',
          'description',
          'unit',
          'frequency',
          'status',
          'submissionDate',
          'standard',
          'standardUnit',
          'indicatorCount',
        ],
        properties: {
          id: { type: 'string', format: 'uuid' },
          name: { type: 'string' },
          category: { type: 'string', enum: ['INM', 'IMP-RS', 'IMPU', 'SPM'] },
          description: { type: 'string' },
          unit: { type: 'string' },
          frequency: {
            type: 'string',
            enum: ['Harian', 'Mingguan', 'Bulanan', 'Triwulan', 'Tahunan'],
          },
          status: { type: 'string', enum: ['Menunggu Persetujuan', 'Diverifikasi', 'Ditolak'] },
          submissionDate: { type: 'string', format: 'date-time' },
          standard: { type: 'number' },
          standardUnit: { type: 'string', enum: ['%', 'menit'] },
          rejectionReason: { type: 'string', nullable: true },
          profileId: { type: 'string' },
          indicatorCount: { type: 'integer', description: 'Jumlah capaian indikator yang tercatat.' },
        },
      },
      SubmittedIndicatorRequest: {
        type: 'object',
        required: ['name', 'category', 'description', 'unit', 'frequency', 'standard', 'standardUnit', 'profileId'],
        properties: {
          name: { type: 'string' },
          category: { type: 'string', enum: ['INM', 'IMP-RS', 'IMPU', 'SPM'] },
          description: { type: 'string' },
          unit: { type: 'string' },
          frequency: {
            type: 'string',
            enum: ['Harian', 'Mingguan', 'Bulanan', 'Triwulan', 'Tahunan'],
          },
          status: { type: 'string', enum: ['Menunggu Persetujuan', 'Diverifikasi', 'Ditolak'] },
          standard: { type: 'number' },
          standardUnit: { type: 'string', enum: ['%', 'menit'] },
          rejectionReason: { type: 'string' },
          profileId: { type: 'string' },
        },
      },
      Indicator: {
        type: 'object',
        required: [
          'id',
          'submissionId',
          'indicator',
          'category',
          'unit',
          'period',
          'frequency',
          'numerator',
          'denominator',
          'calculationMethod',
          'standard',
          'standardUnit',
          'ratio',
          'status',
        ],
        properties: {
          id: { type: 'string', format: 'uuid' },
          submissionId: { type: 'string' },
          indicator: { type: 'string' },
          category: { type: 'string', enum: ['INM', 'IMP-RS', 'IMPU', 'SPM'] },
          unit: { type: 'string' },
          period: { type: 'string', format: 'date-time' },
          frequency: { type: 'string' },
          numerator: { type: 'number' },
          denominator: { type: 'number' },
          calculationMethod: { type: 'string', enum: ['percentage', 'average'] },
          standard: { type: 'number' },
          standardUnit: { type: 'string', enum: ['%', 'menit'] },
          analysisNotes: { type: 'string', nullable: true },
          followUpPlan: { type: 'string', nullable: true },
          ratio: { type: 'string' },
          status: { type: 'string', enum: ['Memenuhi Standar', 'Tidak Memenuhi Standar', 'N/A'] },
        },
      },
      IndicatorRequest: {
        type: 'object',
        required: ['submissionId', 'period', 'numerator', 'denominator'],
        properties: {
          submissionId: { type: 'string' },
          period: { type: 'string', format: 'date' },
          numerator: { type: 'number' },
          denominator: { type: 'number' },
          analysisNotes: { type: 'string' },
          followUpPlan: { type: 'string' },
        },
      },
      Incident: {
        type: 'object',
        required: ['id', 'date', 'status', 'type', 'severity'],
        properties: {
          id: { type: 'string', format: 'uuid' },
          date: { type: 'string', format: 'date-time' },
          status: { type: 'string', enum: ['Investigasi', 'Selesai'] },
          patientName: { type: 'string', nullable: true },
          medicalRecordNumber: { type: 'string', nullable: true },
          careRoom: { type: 'string', nullable: true },
          ageGroup: { type: 'string', nullable: true },
          gender: { type: 'string', nullable: true },
          payer: { type: 'string', nullable: true },
          entryDate: { type: 'string', format: 'date-time', nullable: true },
          entryTime: { type: 'string', nullable: true },
          incidentDate: { type: 'string', format: 'date-time', nullable: true },
          incidentTime: { type: 'string', nullable: true },
          chronology: { type: 'string', nullable: true },
          type: { type: 'string', enum: ['KPC', 'KNC', 'KTC', 'KTD', 'Sentinel'] },
          incidentSubject: { type: 'string', nullable: true },
          incidentLocation: { type: 'string', nullable: true },
          incidentLocationOther: { type: 'string', nullable: true },
          relatedUnit: { type: 'string', nullable: true },
          firstAction: { type: 'string', nullable: true },
          firstActionBy: { type: 'string', nullable: true },
          hasHappenedBefore: { type: 'string', nullable: true },
          severity: { type: 'string', enum: ['biru', 'hijau', 'kuning', 'merah'] },
          patientImpact: { type: 'string', nullable: true },
          analysisNotes: { type: 'string', nullable: true },
          followUpPlan: { type: 'string', nullable: true },
        },
      },
      IncidentRequest: {
        type: 'object',
        required: ['type', 'severity'],
        properties: {
          patientName: { type: 'string' },
          medicalRecordNumber: { type: 'string' },
          careRoom: { type: 'string' },
          ageGroup: { type: 'string' },
          gender: { type: 'string' },
          payer: { type: 'string' },
          entryDate: { type: 'string', format: 'date' },
          entryTime: { type: 'string' },
          incidentDate: { type: 'string', format: 'date' },
          incidentTime: { type: 'string' },
          chronology: { type: 'string' },
          type: { type: 'string', enum: ['KPC', 'KNC', 'KTC', 'KTD', 'Sentinel'] },
          incidentSubject: { type: 'string' },
          incidentLocation: { type: 'string' },
          incidentLocationOther: { type: 'string' },
          relatedUnit: { type: 'string' },
          firstAction: { type: 'string' },
          firstActionBy: { type: 'string' },
          hasHappenedBefore: { type: 'string' },
          severity: { type: 'string', enum: ['biru', 'hijau', 'kuning', 'merah'] },
          patientImpact: { type: 'string' },
          analysisNotes: { type: 'string' },
          followUpPlan: { type: 'string' },
        },
      },
      Risk: {
        type: 'object',
        required: [
          'id',
          'createdAt',
          'unit',
          'source',
          'description',
          'cause',
          'category',
          'consequence',
          'likelihood',
          'cxl',
          'riskLevel',
          'controllability',
          'riskScore',
          'evaluation',
          'actionPlan',
          'status',
        ],
        properties: {
          id: { type: 'string', format: 'uuid' },
          createdAt: { type: 'string', format: 'date-time' },
          unit: { type: 'string' },
          source: { type: 'string' },
          description: { type: 'string' },
          cause: { type: 'string' },
          category: { type: 'string' },
          consequence: { type: 'integer' },
          likelihood: { type: 'integer' },
          cxl: { type: 'integer' },
          riskLevel: { type: 'string', enum: ['Rendah', 'Moderat', 'Tinggi', 'Ekstrem'] },
          controllability: { type: 'integer' },
          riskScore: { type: 'integer' },
          evaluation: { type: 'string', enum: ['Mitigasi', 'Transfer', 'Diterima', 'Dihindari'] },
          actionPlan: { type: 'string' },
          dueDate: { type: 'string', format: 'date-time', nullable: true },
          status: { type: 'string', enum: ['Open', 'InProgress', 'Closed'] },
          residualConsequence: { type: 'integer', nullable: true },
          residualLikelihood: { type: 'integer', nullable: true },
          residualRiskScore: { type: 'integer', nullable: true },
          residualRiskLevel: { type: 'string', nullable: true },
          reportNotes: { type: 'string', nullable: true },
          pic: { type: 'string', nullable: true },
        },
      },
      RiskRequest: {
        type: 'object',
        required: [
          'unit',
          'source',
          'description',
          'cause',
          'category',
          'consequence',
          'likelihood',
          'controllability',
          'evaluation',
          'actionPlan',
        ],
        properties: {
          unit: { type: 'string' },
          source: { type: 'string', enum: [
            'Laporan Insiden',
            'Komplain',
            'Survey Ronde',
            'Rapat Brainstorming',
            'Investigasi',
            'Litigasi',
            'External Requirement',
          ] },
          description: { type: 'string' },
          cause: { type: 'string' },
          category: { type: 'string' },
          consequence: { type: 'integer' },
          likelihood: { type: 'integer' },
          controllability: { type: 'integer' },
          evaluation: { type: 'string' },
          actionPlan: { type: 'string' },
          dueDate: { type: 'string', format: 'date' },
          status: { type: 'string' },
          residualConsequence: { type: 'integer' },
          residualLikelihood: { type: 'integer' },
          residualRiskScore: { type: 'integer' },
          residualRiskLevel: { type: 'string' },
          reportNotes: { type: 'string' },
          pic: { type: 'string' },
        },
      },
      Notification: {
        type: 'object',
        required: ['id', 'timestamp', 'title', 'description', 'isRead'],
        properties: {
          id: { type: 'string', format: 'uuid' },
          timestamp: { type: 'string', format: 'date-time' },
          title: { type: 'string' },
          description: { type: 'string' },
          isRead: { type: 'boolean' },
          link: { type: 'string', nullable: true },
          recipientRole: { type: 'string', nullable: true },
          recipientUnit: { type: 'string', nullable: true },
        },
      },
      NotificationRequest: {
        type: 'object',
        required: ['title', 'description'],
        properties: {
          title: { type: 'string' },
          description: { type: 'string' },
          link: { type: 'string' },
          recipientRole: { type: 'string' },
          recipientUnit: { type: 'string' },
        },
      },
      SystemLog: {
        type: 'object',
        required: ['id', 'timestamp', 'user', 'action', 'details'],
        properties: {
          id: { type: 'string', format: 'uuid' },
          timestamp: { type: 'string', format: 'date-time' },
          user: { type: 'string' },
          action: { type: 'string' },
          details: { type: 'string' },
        },
      },
      SystemLogRequest: {
        type: 'object',
        required: ['user', 'action', 'details'],
        properties: {
          user: { type: 'string' },
          action: { type: 'string' },
          details: { type: 'string' },
        },
      },
    },
  },
  paths: {
    '/api/session': {
      get: {
        tags: ['Session'],
        summary: 'Cek sesi pengguna aktif.',
        responses: {
          200: {
            description: 'Informasi pengguna jika cookie sesi ditemukan.',
            content: { 'application/json': { schema: { $ref: '#/components/schemas/SessionResponse' } } },
          },
        },
      },
    },
    '/api/users': {
      get: {
        tags: ['Users'],
        summary: 'Daftar semua pengguna yang ada.',
        responses: {
          200: {
            description: 'Berhasil memuat daftar pengguna.',
            content: { 'application/json': { schema: { type: 'array', items: { $ref: '#/components/schemas/User' } } } },
          },
          500: { description: 'Gagal memuat pengguna', content: { 'application/json': { schema: errorSchema } } },
        },
      },
      post: {
        tags: ['Users'],
        summary: 'Tambah pengguna baru.',
        requestBody: {
          required: true,
          content: { 'application/json': { schema: { $ref: '#/components/schemas/UserRequest' } } },
        },
        responses: {
          201: { description: 'Pengguna berhasil dibuat.', content: { 'application/json': { schema: { $ref: '#/components/schemas/User' } } } },
          400: { description: 'Validasi gagal', content: { 'application/json': { schema: errorSchema } } },
          500: { description: 'Kesalahan server', content: { 'application/json': { schema: errorSchema } } },
        },
      },
    },
    '/api/users/{id}': {
      patch: {
        tags: ['Users'],
        summary: 'Perbarui data pengguna tertentu.',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/UserRequest' } } } },
        responses: {
          200: { description: 'Data pengguna diperbarui.', content: { 'application/json': { schema: { $ref: '#/components/schemas/User' } } } },
          500: { description: 'Gagal memperbarui', content: { 'application/json': { schema: errorSchema } } },
        },
      },
      delete: {
        tags: ['Users'],
        summary: 'Hapus pengguna berdasarkan ID.',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        responses: {
          200: { description: 'Pengguna terhapus', content: { 'application/json': { schema: { type: 'object', properties: { ok: { type: 'boolean' } } } } } },
          500: { description: 'Gagal menghapus', content: { 'application/json': { schema: errorSchema } } },
        },
      },
    },
    '/api/units': {
      get: {
        tags: ['Units'],
        summary: 'Ambil daftar unit RS.',
        responses: {
          200: { description: 'Daftar unit.', content: { 'application/json': { schema: { type: 'array', items: { $ref: '#/components/schemas/Unit' } } } } },
          500: { description: 'Gagal memuat unit', content: { 'application/json': { schema: errorSchema } } },
        },
      },
      post: {
        tags: ['Units'],
        summary: 'Tambah unit baru.',
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/UnitRequest' } } } },
        responses: {
          201: { description: 'Unit tersimpan.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Unit' } } } },
          400: { description: 'Validasi gagal', content: { 'application/json': { schema: errorSchema } } },
          409: { description: 'Nama unit duplikat', content: { 'application/json': { schema: errorSchema } } },
          500: { description: 'Kesalahan server', content: { 'application/json': { schema: errorSchema } } },
        },
      },
    },
    '/api/units/{id}': {
      patch: {
        tags: ['Units'],
        summary: 'Perbarui nama unit.',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/UnitRequest' } } } },
        responses: {
          200: { description: 'Unit diperbarui.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Unit' } } } },
          409: { description: 'Nama duplikat', content: { 'application/json': { schema: errorSchema } } },
          500: { description: 'Kesalahan server', content: { 'application/json': { schema: errorSchema } } },
        },
      },
      delete: {
        tags: ['Units'],
        summary: 'Hapus unit berdasarkan ID.',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        responses: {
          200: { description: 'Unit terhapus.', content: { 'application/json': { schema: { type: 'object', properties: { ok: { type: 'boolean' } } } } } },
          500: { description: 'Gagal menghapus', content: { 'application/json': { schema: errorSchema } } },
        },
      },
    },
    '/api/profiles': {
      get: {
        tags: ['Indicator Profiles'],
        summary: 'Daftar profil indikator.',
        responses: {
          200: { description: 'Data profil.', content: { 'application/json': { schema: { type: 'array', items: { $ref: '#/components/schemas/IndicatorProfile' } } } } },
          500: { description: 'Kesalahan server', content: { 'application/json': { schema: errorSchema } } },
        },
      },
      post: {
        tags: ['Indicator Profiles'],
        summary: 'Buat profil indikator baru.',
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/IndicatorProfileRequest' } } } },
        responses: {
          201: { description: 'Profil dibuat.', content: { 'application/json': { schema: { $ref: '#/components/schemas/IndicatorProfile' } } } },
          500: { description: 'Kesalahan server', content: { 'application/json': { schema: errorSchema } } },
        },
      },
    },
    '/api/profiles/{id}': {
      patch: {
        tags: ['Indicator Profiles'],
        summary: 'Perbarui profil indikator.',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/IndicatorProfileRequest' } } } },
        responses: {
          200: { description: 'Profil terbarui.', content: { 'application/json': { schema: { $ref: '#/components/schemas/IndicatorProfile' } } } },
          500: { description: 'Gagal memperbarui', content: { 'application/json': { schema: errorSchema } } },
        },
      },
      delete: {
        tags: ['Indicator Profiles'],
        summary: 'Hapus profil indikator.',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        responses: {
          200: { description: 'Profil dihapus.', content: { 'application/json': { schema: { type: 'object', properties: { ok: { type: 'boolean' } } } } } },
          400: { description: 'Profil terkunci', content: { 'application/json': { schema: errorSchema } } },
          500: { description: 'Kesalahan server', content: { 'application/json': { schema: errorSchema } } },
        },
      },
    },
    '/api/submitted-indicators': {
      get: {
        tags: ['Submitted Indicators'],
        summary: 'Daftar pengajuan indikator.',
        responses: {
          200: { description: 'Berhasil.', content: { 'application/json': { schema: { type: 'array', items: { $ref: '#/components/schemas/SubmittedIndicator' } } } } },
          500: { description: 'Kesalahan server', content: { 'application/json': { schema: errorSchema } } },
        },
      },
      post: {
        tags: ['Submitted Indicators'],
        summary: 'Ajukan indikator baru.',
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/SubmittedIndicatorRequest' } } } },
        responses: {
          201: { description: 'Pengajuan dibuat.', content: { 'application/json': { schema: { $ref: '#/components/schemas/SubmittedIndicator' } } } },
          400: { description: 'Validasi gagal', content: { 'application/json': { schema: errorSchema } } },
          500: { description: 'Kesalahan server', content: { 'application/json': { schema: errorSchema } } },
        },
      },
    },
    '/api/submitted-indicators/{id}': {
      patch: {
        tags: ['Submitted Indicators'],
        summary: 'Perbarui pengajuan indikator.',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/SubmittedIndicatorRequest' } } } },
        responses: {
          200: { description: 'Pengajuan diperbarui.', content: { 'application/json': { schema: { $ref: '#/components/schemas/SubmittedIndicator' } } } },
          500: { description: 'Gagal memperbarui', content: { 'application/json': { schema: errorSchema } } },
        },
      },
      delete: {
        tags: ['Submitted Indicators'],
        summary: 'Hapus pengajuan indikator.',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        responses: {
          200: { description: 'Pengajuan dihapus.', content: { 'application/json': { schema: { type: 'object', properties: { ok: { type: 'boolean' } } } } } },
          400: { description: 'Pengajuan terkunci', content: { 'application/json': { schema: errorSchema } } },
          404: { description: 'Tidak ditemukan', content: { 'application/json': { schema: errorSchema } } },
          500: { description: 'Gagal menghapus', content: { 'application/json': { schema: errorSchema } } },
        },
      },
    },
    '/api/indicators': {
      get: {
        tags: ['Indicators'],
        summary: 'Daftar capaian indikator.',
        responses: {
          200: { description: 'Berhasil.', content: { 'application/json': { schema: { type: 'array', items: { $ref: '#/components/schemas/Indicator' } } } } },
          500: { description: 'Kesalahan server', content: { 'application/json': { schema: errorSchema } } },
        },
      },
      post: {
        tags: ['Indicators'],
        summary: 'Catat capaian indikator baru.',
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/IndicatorRequest' } } } },
        responses: {
          201: { description: 'Capaian tercatat.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Indicator' } } } },
          400: { description: 'Validasi gagal', content: { 'application/json': { schema: errorSchema } } },
          500: { description: 'Kesalahan server', content: { 'application/json': { schema: errorSchema } } },
        },
      },
    },
    '/api/indicators/{id}': {
      patch: {
        tags: ['Indicators'],
        summary: 'Perbarui capaian indikator.',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/IndicatorRequest' } } } },
        responses: {
          200: { description: 'Capaian diperbarui.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Indicator' } } } },
          404: { description: 'Tidak ditemukan', content: { 'application/json': { schema: errorSchema } } },
          500: { description: 'Gagal memperbarui', content: { 'application/json': { schema: errorSchema } } },
        },
      },
      delete: {
        tags: ['Indicators'],
        summary: 'Hapus capaian indikator.',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        responses: {
          200: { description: 'Capaian terhapus.', content: { 'application/json': { schema: { type: 'object', properties: { ok: { type: 'boolean' } } } } } },
          500: { description: 'Gagal menghapus', content: { 'application/json': { schema: errorSchema } } },
        },
      },
    },
    '/api/incidents': {
      get: {
        tags: ['Incidents'],
        summary: 'Daftar insiden keselamatan.',
        responses: {
          200: { description: 'Berhasil.', content: { 'application/json': { schema: { type: 'array', items: { $ref: '#/components/schemas/Incident' } } } } },
          500: { description: 'Kesalahan server', content: { 'application/json': { schema: errorSchema } } },
        },
      },
      post: {
        tags: ['Incidents'],
        summary: 'Laporkan insiden baru.',
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/IncidentRequest' } } } },
        responses: {
          201: { description: 'Insiden tercatat.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Incident' } } } },
          400: { description: 'Validasi gagal', content: { 'application/json': { schema: errorSchema } } },
          500: { description: 'Kesalahan server', content: { 'application/json': { schema: errorSchema } } },
        },
      },
    },
    '/api/incidents/{id}': {
      patch: {
        tags: ['Incidents'],
        summary: 'Perbarui detail insiden.',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/IncidentRequest' } } } },
        responses: {
          200: { description: 'Insiden diperbarui.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Incident' } } } },
          500: { description: 'Gagal memperbarui', content: { 'application/json': { schema: errorSchema } } },
        },
      },
      delete: {
        tags: ['Incidents'],
        summary: 'Hapus insiden.',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        responses: {
          200: { description: 'Insiden dihapus.', content: { 'application/json': { schema: { type: 'object', properties: { ok: { type: 'boolean' } } } } } },
          500: { description: 'Gagal menghapus', content: { 'application/json': { schema: errorSchema } } },
        },
      },
    },
    '/api/risks': {
      get: {
        tags: ['Risks'],
        summary: 'Daftar risiko terdaftar.',
        responses: {
          200: { description: 'Berhasil.', content: { 'application/json': { schema: { type: 'array', items: { $ref: '#/components/schemas/Risk' } } } } },
          500: { description: 'Kesalahan server', content: { 'application/json': { schema: errorSchema } } },
        },
      },
      post: {
        tags: ['Risks'],
        summary: 'Catat risiko baru.',
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/RiskRequest' } } } },
        responses: {
          201: { description: 'Risiko tercatat.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Risk' } } } },
          500: { description: 'Kesalahan server', content: { 'application/json': { schema: errorSchema } } },
        },
      },
    },
    '/api/risks/{id}': {
      patch: {
        tags: ['Risks'],
        summary: 'Perbarui risiko.',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/RiskRequest' } } } },
        responses: {
          200: { description: 'Risiko diperbarui.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Risk' } } } },
          500: { description: 'Gagal memperbarui', content: { 'application/json': { schema: errorSchema } } },
        },
      },
      delete: {
        tags: ['Risks'],
        summary: 'Hapus risiko.',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        responses: {
          200: { description: 'Risiko terhapus.', content: { 'application/json': { schema: { type: 'object', properties: { ok: { type: 'boolean' } } } } } },
          500: { description: 'Gagal menghapus', content: { 'application/json': { schema: errorSchema } } },
        },
      },
    },
    '/api/notifications': {
      get: {
        tags: ['Notifications'],
        summary: 'Ambil notifikasi sesuai role/unit.',
        parameters: [
          { name: 'role', in: 'query', required: false, schema: { type: 'string' } },
          { name: 'unit', in: 'query', required: false, schema: { type: 'string' } },
        ],
        responses: {
          200: { description: 'Daftar notifikasi.', content: { 'application/json': { schema: { type: 'array', items: { $ref: '#/components/schemas/Notification' } } } } },
          500: { description: 'Kesalahan server', content: { 'application/json': { schema: errorSchema } } },
        },
      },
      post: {
        tags: ['Notifications'],
        summary: 'Kirim notifikasi baru.',
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/NotificationRequest' } } } },
        responses: {
          201: { description: 'Notifikasi dibuat.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Notification' } } } },
          400: { description: 'Validasi gagal', content: { 'application/json': { schema: errorSchema } } },
          500: { description: 'Kesalahan server', content: { 'application/json': { schema: errorSchema } } },
        },
      },
    },
    '/api/logs': {
      get: {
        tags: ['System Logs'],
        summary: 'Ambil catatan audit.',
        responses: {
          200: { description: 'Berhasil.', content: { 'application/json': { schema: { type: 'array', items: { $ref: '#/components/schemas/SystemLog' } } } } },
          500: { description: 'Kesalahan server', content: { 'application/json': { schema: errorSchema } } },
        },
      },
      post: {
        tags: ['System Logs'],
        summary: 'Simpan catatan audit.',
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/SystemLogRequest' } } } },
        responses: {
          201: { description: 'Log tersimpan.', content: { 'application/json': { schema: { $ref: '#/components/schemas/SystemLog' } } } },
          400: { description: 'Validasi gagal', content: { 'application/json': { schema: errorSchema } } },
          500: { description: 'Kesalahan server', content: { 'application/json': { schema: errorSchema } } },
        },
      },
    },
    '/api/realtime': {
      get: {
        tags: ['Realtime'],
        summary: 'Stream event SSE untuk profil, indikator, dan notifikasi.',
        responses: {
          200: {
            description: 'Aliran Server-Sent Events.',
            content: { 'text/event-stream': { schema: { type: 'string', example: 'data: {"event":"profile:created"}\n\n' } } },
          },
        },
      },
    },
  },
} satisfies OpenAPIObject
